"""
FastAPI API template (generated by builder-v1).

This is a minimal service skeleton intended to be copied into a new repo.
You can safely modify/extend it after generation.

Project: {{ repo_name }}
"""

from fastapi import FastAPI

app = FastAPI(title="{{ repo_name }}")


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


